In [1]:
# datainput

In [188]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [189]:
df = pd.read_csv("C:\\Users\\axay1\\Downloads\\titanic (1).csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [190]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [191]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [192]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [193]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [194]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [195]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [196]:
df['Age'].fillna(df['Age'].median(), inplace = True)

In [197]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [198]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [199]:
gender_dummies = pd.get_dummies(df['Sex'], drop_first= True)
df =pd.concat ([df , gender_dummies], axis = 1)
df.drop('Sex',axis = 1 , inplace = True)

In [200]:
df.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name   Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris  22.0      1      0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0
2                               Heikkinen, Miss. Laina  26.0      0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0
4                             Allen, Mr. William Henry  35.0      0      0
..                                                 ...   ...    ...    ...
886                              Montvila, Rev. Juozas  27.0      0      0
887                       Graham, Miss. Margaret Edith  19.0      0      0
888           Johnston, Miss. Catherine Helen "Carrie"  28.0      1      2
889                              Behr, Mr. Karl Howell  26.0      0      0
890                                Dooley, Mr. Patrick  32.0      0      0

               Ticket     Fare Cabin Embarked   male
0           A/5 21171   7.2500   NaN        S   True
1            PC 17599  71.2833   C85        C  False
2    STON/O2. 3101282   7.9250   NaN        S  False
3              113803  53.1000  C123        S  False
4              373450   8.0500   NaN        S   True
..                ...      ...   ...      ...    ...
886            211536  13.0000   NaN        S   True
887            112053  30.0000   B42        S  False
888        W./C. 6607  23.4500   NaN        S  False
889            111369  30.0000  C148        C   True
890            370376   7.7500   NaN        Q   True

[891 rows x 12 columns]>

In [201]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [202]:
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True, dtype=int)

In [203]:
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,True,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,False,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,False,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,False,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,True,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,False,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",28.0,1,2,W./C. 6607,23.4500,NaN,False,0,1
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,True,0,0
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,True,1,0

In [204]:
x  = df[["male","Embarked_Q","Embarked_S","Age","Pclass","Fare","SibSp","Parch"]]

In [205]:
y =df ["Survived"]

x_train,x_test,y_train,y_test = train_test_split(x , y ,test_size=0.2 ,random_state = 42 )
x_train

In [206]:
x_train,x_test,y_train,y_test = train_test_split(x , y ,test_size=0.2 ,random_state = 42 )
x_train

      male  Embarked_Q  Embarked_S   Age  Pclass      Fare  SibSp  Parch
331   True           0           1  45.5       1   28.5000      0      0
733   True           0           1  23.0       2   13.0000      0      0
382   True           0           1  32.0       3    7.9250      0      0
704   True           0           1  26.0       3    7.8542      1      0
813  False           0           1   6.0       3   31.2750      4      2
..     ...         ...         ...   ...     ...       ...    ...    ...
106  False           0           1  21.0       3    7.6500      0      0
270   True           0           1  28.0       1   31.0000      0      0
860   True           0           1  41.0       3   14.1083      2      0
435  False           0           1  14.0       1  120.0000      1      2
102   True           0           1  21.0       1   77.2875      0      1

[712 rows x 8 columns]

In [207]:
log = LogisticRegression()
log.fit(x_train,y_train)

C:\Users\axay1\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [209]:
pred = log.predict(x_test)
accuracy = accuracy_score(y_test, pred) * 100
print("Mera model Itana sikha hai:", accuracy)

Mera model Itana sikha hai: 79.88826815642457

In [211]:
from sklearn.metrics import recall_score

recall = recall_score(y_test, pred)
print("Recall:", recall)

Recall: 0.7297297297297297

In [212]:
from sklearn.metrics import precision_score

precision = precision_score(y_test, pred)
print("Precision:", precision)

Precision: 0.7714285714285715

In [213]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, pred)
print("F1 Score:", f1)

F1 Score: 0.75